export type Ticket = {
  id: string;
  name: string;
  description: string;
  category_raw: string;
  category: string;
  priority: string;
  status: string;
  is_open: boolean;
  owner: string | null;
  customer_name: string | null;
  rid: string | null;
  pid: string | null;
  create_date: string | null;
  close_date: string | null;
  resolution_time_hours: number | null;
  resolution_notes: string;
  resolution_type: string;
  root_causes: string[];
  cost: number;
  cost_paid_by: string;
  csat: string | null;
  created_by: string;
  is_repeat_property_issue: boolean;
  is_repeat_customer_issue: boolean;
  repeat_count_property: number;
  repeat_count_customer: number;
  days_since_first_ticket: number | null;
  is_first_week_ticket: boolean;
  is_first_month_ticket: boolean;
  is_onboarding_issue: boolean;
  is_communication_gap: boolean;
  is_self_serve_possible: boolean;
  is_visibility_issue: boolean;
  is_preventable: boolean;
  is_automation_opportunity: boolean;
  frustration_score: number;
  preventability_score: number;
  ux_issues: string[];
  ux_theme: string;
};

export type InsightCard = {
  type: string;
  severity: string;
  title: string;
  description: string;
  recommendation: string;
};

export type Insights = {
  summary: {
    total_tickets: number;
    open_tickets: number;
    closed_tickets: number;
    preventable_count: number;
    preventable_pct: number;
    onboarding_count: number;
    onboarding_pct: number;
    communication_count: number;
    communication_pct: number;
    self_serve_count: number;
    self_serve_pct: number;
    visibility_count: number;
    visibility_pct: number;
    automation_count: number;
    automation_pct: number;
    repeat_property_count: number;
    repeat_property_pct: number;
    first_week_count: number;
    first_week_pct: number;
    first_month_count: number;
    first_month_pct: number;
    zero_effort_count: number;
    zero_effort_pct: number;
    avg_resolution_hours: number;
    median_resolution_hours: number;
    total_cost: number;
    preventable_cost: number;
  };
  category_distribution: { name: string; value: number }[];
  theme_distribution: { name: string; value: number }[];
  ux_issue_distribution: { name: string; value: number }[];
  resolution_type_distribution: { name: string; value: number }[];
  root_cause_distribution: { name: string; value: number }[];
  monthly_trend: { month: string; tickets: number; preventable: number }[];
  frustration_by_theme: { theme: string; score: number }[];
  resolution_by_category: {
    category: string;
    avg_hours: number;
    median_hours: number;
  }[];
  cost_by_category: { category: string; cost: number }[];
  top_repeat_property_issues: {
    property: string;
    category: string;
    count: number;
  }[];
  property_health: {
    rid: string;
    total_tickets: number;
    open_tickets: number;
    avg_frustration: number;
    recurring_categories: number;
    total_cost: number;
    health_score: number;
  }[];
  first_week_by_theme: { theme: string; count: number }[];
  repeat_customers: { name: string; tickets: number }[];
  ai_insights: InsightCard[];
};
